# Generated by Django 2.2.6 on 2019-10-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('mid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('details', models.CharField(max_length=150)),
                ('available', models.BooleanField(default=True)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('tid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('sid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('machines', models.ManyToManyField(to='main.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('sid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('stages', models.ManyToManyField(to='main.Stage')),
            ],
        ),
    ]
