# Generated by Django 2.2.6 on 2019-10-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('main', '0002_auto_20191019_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='cid',
            new_name='sid',
        ),
        migrations.AddField(
            model_name='crop',
            name='tips',
            field=models.ManyToManyField(to='main.Tip'),
        ),
    ]
