# Generated by Django 2.2.6 on 2019-10-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_remove_crop_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='tips',
            field=models.ManyToManyField(to='main.Tip'),
        ),
    ]
