# Generated by Django 2.2.6 on 2019-10-19 08:18

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('main', '0005_crop_tips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='sid',
            new_name='cid',
        ),
    ]
