# Generated by Django 2.2.6 on 2019-10-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_stage_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='tips',
            field=models.ManyToManyField(blank=True, to='main.Tip'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='tips',
            field=models.ManyToManyField(blank=True, to='main.Tip'),
        ),
    ]
